# Generated by Django 4.2.1 on 2023-06-02 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Crops',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('variety', models.CharField(max_length=20)),
                ('planting_date', models.DateField()),
                ('description', models.TextField()),
                ('quantity', models.IntegerField()),
                ('is_harvested', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'crops',
            },
        ),
    ]
