# Generated by Django 4.2.1 on 2023-06-07 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home_page', '0002_crops_cid'),
    ]

    operations = [
        migrations.CreateModel(
            name='Animals',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Aid', models.CharField(default=0, max_length=1000000)),
                ('picture', models.ImageField(upload_to='animal_pictures')),
                ('name', models.CharField(max_length=20)),
                ('age', models.IntegerField()),
                ('production', models.DecimalField(decimal_places=2, max_digits=3)),
            ],
        ),
    ]
