# Generated by Django 4.2.1 on 2023-06-07 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home_page', '0003_animals'),
    ]

    operations = [
        migrations.AlterField(
            model_name='animals',
            name='production',
            field=models.DecimalField(decimal_places=2, max_digits=3),
        ),
    ]
