# Generated by Django 4.2.1 on 2023-06-10 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home_page', '0004_alter_animals_production'),
    ]

    operations = [
        migrations.CreateModel(
            name='Machinery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number_plate', models.CharField(max_length=20, unique=True)),
                ('model', models.CharField(max_length=20)),
                ('description', models.TextField()),
                ('manufacture_year', models.IntegerField()),
                ('purchase_date', models.DateField()),
                ('purchase_price', models.DecimalField(decimal_places=2, max_digits=3)),
            ],
            options={
                'db_table': 'machinery',
            },
        ),
    ]
