# Generated by Django 4.2.1 on 2023-06-10 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home_page', '0005_machinery'),
    ]

    operations = [
        migrations.AlterField(
            model_name='machinery',
            name='purchase_price',
            field=models.DecimalField(decimal_places=2, max_digits=30),
        ),
    ]
