# Generated by Django 4.2.1 on 2023-06-13 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home_page', '0008_alter_machinery_number_plate'),
    ]

    operations = [
        migrations.CreateModel(
            name='Expenses',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Eid', models.CharField(default=1, max_length=1000)),
                ('date', models.DateField()),
                ('description', models.TextField()),
                ('amount', models.BigIntegerField()),
                ('receipt', models.FileField(blank=True, null=True, upload_to='expenses/')),
            ],
            options={
                'db_table': 'expense',
            },
        ),
        migrations.RemoveField(
            model_name='machinery',
            name='id',
        ),
        migrations.AlterField(
            model_name='machinery',
            name='number_plate',
            field=models.CharField(max_length=20, primary_key=True, serialize=False),
        ),
    ]
