# Generated by Django 4.2.1 on 2023-06-14 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home_page', '0009_expenses_remove_machinery_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='expenses',
            name='id',
        ),
        migrations.AlterField(
            model_name='expenses',
            name='Eid',
            field=models.IntegerField(default=1, primary_key=True, serialize=False),
        ),
    ]
