# Generated by Django 4.2.1 on 2023-06-16 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home_page', '0012_overview'),
    ]

    operations = [
        migrations.CreateModel(
            name='Employees',
            fields=[
                ('Eid', models.IntegerField(default=1, primary_key=True, serialize=False)),
                ('Name', models.CharField(max_length=20)),
                ('Position', models.CharField(max_length=20)),
                ('Salary', models.IntegerField()),
                ('Performance', models.CharField(max_length=20)),
            ],
            options={
                'db_table': 'emloyees',
            },
        ),
    ]
